apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.30.3
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: k6-config
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 15s

#     scrape_configs:
#       - job_name: 'prometheus'
#         static_configs:
#           - targets: ['prometheus.k6.svc.cluster.local:9090']

#     remote_write:
#       - url: 'http:/prometheus.k6.svc.cluster.local:9090/api/v1/write'
#         write_relabel_configs:
#           - source_labels: ['__name__']
#             target_label: '__name__'
#             replacement: '$1'