apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    remote_write:
      - url: 'http://localhost:9090/api/v1/write'
        remote_timeout: 30s
        queue_config:
          capacity: 10000
          min_backoff: 2s
          max_backoff: 10s
          max_samples_per_send: 1000