apiVersion: v1
kind: Service
metadata:
  name: k6-prometheus
  labels:
    app: k6-prometheus
spec:
  selector:
    app: k6-prometheus
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: write
      protocol: TCP
      port: 9091
      targetPort: 9091

