global:
    scrape_interval: 5s

scrape_configs:

  - job_name: k6_vus
    metrics_path: /probe
    params:
      module: ['k6_vus']
      target: ['http://prometheus:9090/api/v1/query?query=k6_vus']
    static_configs:
      - targets: ['192.168.1.6:7979']

  - job_name: k6_vus_max
    metrics_path: /probe
    params:
      module: ['k6_vus_max']
      target: ['http://prometheus:9090/api/v1/query?query=k6_vus_max']
    static_configs:
      - targets: ['192.168.1.6:7979']

  - job_name: k6_data_received_total
    metrics_path: /probe
    params:
      module: ['k6_data_received_total']
      target: ['http://prometheus:9090/api/v1/query?query=k6_data_received_total']
    static_configs:
      - targets: ['192.168.1.6:7979']



  # - job_name: 'federate'
  #   scrape_interval: 15s
  #   honor_labels: true
  #   metrics_path: '/federate'
  #   params:
  #     'match[]':
  #       - '{job="prometheus-sub"}'
  #       - '{__name__=~"job:.*"}'
  #   static_configs:
  #     - targets:
  #       - 'localhost:9090'

remote_write:
  - url: 'http://localhost:9090/api/v1/write'
    name: k6write
    send_exemplars: true
    send_native_histograms: true
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      min_backoff: 2s
      max_backoff: 10s
      max_samples_per_send: 1000

# remote_read:
#   - url: 'http://localhost:9090/api/v1/read'
#     name: k6read
#     read_recent: true
  
# rule_files:
#   - /prometheus/rules.yml
