---
modules:
  default:
  k6_vus:
    metrics:
    - name: k6
      type: object
      path: '{ .data }'
      epochTimestamp: '{ .timestamp }'
      help: counter
      valuetype: counter
      values:
        vus: '{ .result[-1].value[1] }'
  k6_vus_max:
    metrics:
    - name: k6
      type: object
      path: '{ .data }'
      epochTimestamp: '{ .timestamp }'
      help: Example of a timestamped value scrape in the json
      valuetype: counter
      values:
        vus_max: '{ .result[-1].value[1] }'
  k6_data_received_total:
    metrics:
    - name: k6
      type: object
      path: '{ .data }'
      epochTimestamp: '{ .timestamp }'
      help: Example of a timestamped value scrape in the json
      valuetype: gauge
      values:
        data_received_total: '{ .result[-1].value[1] }'